import {
  Activity, Archive, Bot, Briefcase, Building2, Cloud, Code, Coins, Cpu, Database, Eye, FileText, GitBranch,
  Gauge, Globe, Handshake, HardDrive, History, KeyRound, Layers, LayoutDashboard, Link2, LockKeyhole, Moon,
  Package, PencilLine, RefreshCw, Rocket, ScrollText, Server, ShieldCheck, Sparkles, SquareTerminal, Tag,
  UsersRound, Wrench,
} from "lucide-react";
import type { Icon } from "@shpyrd/content/site/landings";

// The icons the feature and solution pages name (content/site/landings.ts),
// drawn: on their pages and in the header's menus.
export const icons: Record<Icon, React.ReactElement> = {
  rocket: <Rocket />,
  cloud: <Cloud />,
  database: <Database />,
  lock: <LockKeyhole />,
  moon: <Moon />,
  activity: <Activity />,
  git: <GitBranch />,
  terminal: <SquareTerminal />,
  globe: <Globe />,
  history: <History />,
  shield: <ShieldCheck />,
  archive: <Archive />,
  server: <Server />,
  cpu: <Cpu />,
  "hard-drive": <HardDrive />,
  users: <UsersRound />,
  key: <KeyRound />,
  layout: <LayoutDashboard />,
  bot: <Bot />,
  sparkles: <Sparkles />,
  link: <Link2 />,
  pencil: <PencilLine />,
  briefcase: <Briefcase />,
  building: <Building2 />,
  handshake: <Handshake />,
  tag: <Tag />,
  layers: <Layers />,
  scroll: <ScrollText />,
  gauge: <Gauge />,
  code: <Code />,
  file: <FileText />,
  wrench: <Wrench />,
  refresh: <RefreshCw />,
  eye: <Eye />,
  coins: <Coins />,
  package: <Package />,
};
